language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
install:
    - pip install .[all_tokenizers]
    - pip install coveralls
script:
    - coverage run --source=toiro setup.py test
after_success:
    - coveralls
